### ISSUE TITLE
Dirt doesn't drop with the mod installed

### ISSUE THREAD

**Issue by SamuelMC01** [k3nder/blocksExpasion#3]
i just installed the mod and noticed that dirt didn't drop anymore, but just dirt, grass, pathed dirt and farmland did drop

**Comment by k3nder** [comment]
Please can you add images that show the error.

**Comment by SamuelMC01** [comment]
https://github.com/k3nder/blocksExpasion/assets/146004141/bdc75ab4-978e-4e72-bd0a-448ee6731738

demonstration of the bug

**Comment by k3nder** [comment]
Thanks for reporting the error, I put it as a test and apparently I forgot to remove it

**Comment by k3nder** [comment]
It is already solved in the repository, then I will upload it to
