### ISSUE TITLE
Blocks not rendering on Xaero's maps

### ISSUE THREAD

**Issue by cecaelion** [k3nder/blocksExpasion#4]
Mods: blocksExpansion/brixpansion, Xaero's World Map, Xaero's Minimap, Fabric API/QFAPI
Loader: Fabric & Quilt
Issue: BlocksExpansion blocks do not appear on either of Xaero's maps. While it's difficult to see on the minimap, the blocks just do not exist on the world map (they should be in the 5x5 area where a few dirt blocks are). 

![2024-01-05_14 18 51](https://github.com/k3nder/blocksExpasion/assets/10005837/6e69ccc0-d0ac-49e4-b4a4-74c2ad99462b)
![2024-01-05_14 19 00](https://github.com/k3nder/blocksExpasion/assets/10005837/e0f3afb8-4b96-492d-84cf-0ec3faaec604)

**Comment by k3nder** [comment]
Thank you for reporting the error, I have already solved it, it will be fixed in the next update of the mod, it was fixed by cloning the configuration of the parent block to its derivatives
