### ISSUE TITLE
Tile drops.

### ISSUE THREAD

**Issue by Orlinia** [k3nder/blocksExpasion#9]
When added to the game dirt does not drop after being mined. To my knowledge this issue only affects dirt blocks only but may affect some other blocks. (I did not test all vanilla and modded blocks to find out if more have this issue.)

**Comment by k3nder** [comment]
ya se arreglo en otras versiones

**Comment by AverageStardust** [comment]
No it hasn't been fixed, this still happens in the newest version for Minecraft 1.20.1 (blocksExpasion 1.2)
